spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
        - id: policy-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/policies/**
          filters:
            - StripPrefix=1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
